test circle

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,13 +12,6 @@ executors:
 jobs:
   build_and_push_docker:
     executor: docker-executor
-    parameters:
-      service:
-        type: string
-      dockerfile:
-        type: string
-      ecr_repo:
-        type: string
     steps:
       - checkout
       - setup_remote_docker:
@@ -27,125 +20,128 @@ jobs:
           role_arn: '${AWS_ECR_DEPLOY_ARN}'
           role_session_name: '${AWS_SESSION_NAME}'
           profile_name: ecr-publisher
+      - checkout
+      - attach_workspace:
+          at: ~/project
       - run:
-          name: Build Docker image (<< parameters.service >>)
+          name: Write Git SHA to version file
           command: |
-            export COMMIT_SHA="${CIRCLE_SHA1}"
-            docker build \
-              -f << parameters.dockerfile >> \
-              -t "${AWS_ECR_ACCOUNT}/<< parameters.ecr_repo >>:${COMMIT_SHA}" \
-              .
-            docker tag "${AWS_ECR_ACCOUNT}/<< parameters.ecr_repo >>:${COMMIT_SHA}" "${AWS_ECR_ACCOUNT}/<< parameters.ecr_repo >>:latest"
+            echo "VERSION=${CIRCLE_SHA1}" > version.txt
+      - run:
+          name: Build docker images
+          command: |
+            docker build -t ${AWS_ECR_ACCOUNT}/fimento/hook0-api:latest --build-arg FEATURES="application-secret-compatibility" -f ./api/Dockerfile . &
+            docker build -t ${AWS_ECR_ACCOUNT}/fimento/hook0-frontend:latest -f ./frontend/Dockerfile . &
+            docker build -t ${AWS_ECR_ACCOUNT}/fimento/hook0-output-worker:latest -f ./output-worker/Dockerfile . &
+            wait
       - run:
           name: Authenticate to ECR
           command: |
             aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | docker login --username AWS "${AWS_ECR_ACCOUNT}" --password-stdin
       - run:
-          name: Push to ECR (<< parameters.service >>)
+          name: Push to ECR
           command: |
-            docker push "${AWS_ECR_ACCOUNT}/<< parameters.ecr_repo >>:latest"
-            docker push "${AWS_ECR_ACCOUNT}/<< parameters.ecr_repo >>:${CIRCLE_SHA1}"
-
+            echo "Pushing Docker images..."
+            docker tag "${AWS_ECR_ACCOUNT}/fimento/hook0-api:latest" "${AWS_ECR_ACCOUNT}/fimento/hook0-api:${CIRCLE_SHA1}"
+            docker tag "${AWS_ECR_ACCOUNT}/fimento/hook0-frontend:latest" "${AWS_ECR_ACCOUNT}/fimento/hook0-frontend:${CIRCLE_SHA1}"
+            docker tag "${AWS_ECR_ACCOUNT}/fimento/hook0-output-worker:latest" "${AWS_ECR_ACCOUNT}/fimento/hook0-output-worker:${CIRCLE_SHA1}"
+            docker push "${AWS_ECR_ACCOUNT}/fimento/hook0-api:latest"
+            docker push "${AWS_ECR_ACCOUNT}/fimento/hook0-api:${CIRCLE_SHA1}"
+            docker push "${AWS_ECR_ACCOUNT}/fimento/hook0-frontend:latest"
+            docker push "${AWS_ECR_ACCOUNT}/fimento/hook0-frontend:${CIRCLE_SHA1}"
+            docker push "${AWS_ECR_ACCOUNT}/fimento/hook0-output-worker:latest"
+            docker push "${AWS_ECR_ACCOUNT}/fimento/hook0-output-worker:${CIRCLE_SHA1}"
   update_k8s_image_and_sync:
+    # This job updates the `image.tag` field in `k8s/{deploy_environment}.values.yaml`.
+    # When updated, ArgoCD detects the change and deploys the specified image tag in
+    # the corresponding Kubernetes environment.
     executor: docker-executor
+    environment:
+      AWS_DEFAULT_REGION: eu-north-1
+      ECR_REGISTRY: 711387106999.dkr.ecr.eu-north-1.amazonaws.com
     steps:
       - checkout
+      - attach_workspace:
+          at: /tmp/workspace
       - run:
           name: Set Deploy Environment
           command: |
             echo 'export DEPLOY_ENVIRONMENT=sandbox' >> "${BASH_ENV}"
+            echo "Set DEPLOY_ENVIRONMENT to 'sandbox'. Staging and production are not yet implemented."
       - run:
           name: Load Commit SHA
           command: |
             IMAGE_TAG="${CIRCLE_SHA1}"
             echo "export IMAGE_TAG=${IMAGE_TAG}" >> "${BASH_ENV}"
-            echo "Using IMAGE_TAG: ${IMAGE_TAG}"
+            echo "Using IMAGE_TAG: $IMAGE_TAG"
       - aws-cli/setup:
           role_arn: '${AWS_ROLE_ARN}'
           role_session_name: '${AWS_SESSION_NAME}'
       - run:
           name: Authenticate to ECR
           command: |
-            aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | docker login --username AWS --password-stdin "${AWS_ECR_ACCOUNT}"
+            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}
+      - run:
+          name: Verify Image Tags Exist in ECR
+          command: |
+            for REPO in fimento/hook0-api fimento/hook0-frontend fimento/hook0-output-worker; do
+              IMAGE_EXISTS=$(aws ecr describe-images --region eu-north-1 --repository-name ${REPO} --image-ids imageTag=$IMAGE_TAG || echo "NOT_FOUND")
+              if [ "$IMAGE_EXISTS" = "NOT_FOUND" ]; then
+                echo "Error: Image with tag $IMAGE_TAG does not exist in repository $REPO. Exiting."
+                exit 1
+              fi
+              echo "Image with tag $IMAGE_TAG exists in $REPO."
+            done
       - run:
           name: Update image.tag in values.yaml
           command: |
-            yq -i ".api.image.tag = \"${IMAGE_TAG}\"" k8s/values.yaml
-            yq -i ".frontend.image.tag = \"${IMAGE_TAG}\"" k8s/values.yaml
-            yq -i ".outputWorker.image.tag = \"${IMAGE_TAG}\"" k8s/values.yaml
+            for VALUES_FILE in k8s/values.yaml k8s/values.demo.yaml; do
+              yq -i ".api.image.tag = \"$IMAGE_TAG\"" "$VALUES_FILE"
+              yq -i ".frontend.image.tag = \"$IMAGE_TAG\"" "$VALUES_FILE"
+              yq -i ".outputWorker.image.tag = \"$IMAGE_TAG\"" "$VALUES_FILE"
+            done
       - run:
           name: Commit and Push Updated Values File
           command: |
+            # Save the bot key to a file
             touch ~/.ssh/botkey
             echo "-----BEGIN OPENSSH PRIVATE KEY-----" >> ~/.ssh/botkey
-            echo "${FIMENTOBOT_KEY}" >> ~/.ssh/botkey
+            echo "$FIMENTOBOT_KEY" >> ~/.ssh/botkey
             echo "-----END OPENSSH PRIVATE KEY-----" >> ~/.ssh/botkey
-            echo "${FIMENTOBOT_KEY_PUB}" > ~/.ssh/botkey.pub
+            echo "$FIMENTOBOT_KEY_PUB" > ~/.ssh/botkey.pub
             chmod 600 ~/.ssh/botkey
             ssh-keyscan github.com >> ~/.ssh/known_hosts
             eval "$(ssh-agent -s)"
             ssh-add ~/.ssh/botkey
 
+            # Configure Git to use the bot key for signing
             git config --global user.signingkey ~/.ssh/botkey
             git config --global gpg.format ssh
             git config --global commit.gpgSign true
             git config user.name "fimentobot"
             git config user.email "devops+circleci@fimento.com"
-            CURRENT_BRANCH="${CIRCLE_BRANCH}"
+            CURRENT_BRANCH=$CIRCLE_BRANCH
             git add k8s/values*.yaml
-            git commit -S -m "Update Hook0 image tags to ${IMAGE_TAG:0:8}... for ${DEPLOY_ENVIRONMENT} [skip ci]"
-            git push origin "${CURRENT_BRANCH}"
+            git commit -S -m "Update image.tag to ${IMAGE_TAG:0:8}... for $DEPLOY_ENVIRONMENT [skip ci]"
+            git push origin $CURRENT_BRANCH
 
 workflows:
   version: 2
-  build-push-deploy:
+  build_push_deploy:
     jobs:
-      # Build all 3 images in parallel
       - build_and_push_docker:
-          name: build-api
-          service: api
-          dockerfile: api/Dockerfile
-          ecr_repo: hook0/api
-          context:
-            - circleci-ecr-deploy
+          context: circleci-ecr-deploy
           filters:
             branches:
               only:
-                - fimento/local-dev-setup
-
-      - build_and_push_docker:
-          name: build-frontend
-          service: frontend
-          dockerfile: frontend/Dockerfile
-          ecr_repo: hook0/frontend
-          context:
-            - circleci-ecr-deploy
-          filters:
-            branches:
-              only:
-                - fimento/local-dev-setup
-
-      - build_and_push_docker:
-          name: build-output-worker
-          service: output-worker
-          dockerfile: output-worker/Dockerfile
-          ecr_repo: hook0/output-worker
-          context:
-            - circleci-ecr-deploy
-          filters:
-            branches:
-              only:
-                - fimento/local-dev-setup
-
+                - master
       - update_k8s_image_and_sync:
           requires:
-            - build-api
-            - build-frontend
-            - build-output-worker
+            - build_and_push_docker
           context:
             - circleci-ecr-deploy
             - fimentobot-ci
           filters:
             branches:
               only:
-                - fimento/local-dev-setup
+                - master
